config/routes.rb
MindGame::Application.routes.draw do

  get "set_language/english"

  get "set_language/hebrew"

  get "instructions/create"

  get "games/show"

  get "games/index"

  get "statistics/create"

root to: 'static_pages#home'

resources :games
resources :instructions
resources :statistics
resources :therapists
resources :patients do
  get 'show_details_to_therapist', :on => :member
end

resources :sessions, only: [:new, :create, :destroy]

get '/help',    to: 'static_pages#help'
get '/about',   to: 'static_pages#about'
get '/contact', to: 'static_pages#contact'

get '/signup', to: 'therapists#new'
get '/patient_signup', to: 'patients#new'

get '/signin',  to: 'sessions#new'
get '/signout', to: 'sessions#destroy', via: :delete

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :statistics
  has_many :patients, :through => :statistics
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
  	@game = Game.find(params[:id])
  	render :file => Rails.root.join('app', 'views', 'games', 'game' + params[:id].to_s, 'game')
  end

  def index
  	@games = Game.all
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.he.html.erb
<% provide(:title, 'כל המשחקים') %>
<h1>כל המשחקים</h1>

<ul class="users">
  <% @games.each do |game| %>
    <li>
      <%= link_to game.name, game_path(game) %>
    </li>
  <% end %>
</ul>

app/views/games/index.html.erb
<% provide(:title, 'All games') %>
<h1>All games</h1>

<ul class="users">
  <% @games.each do |game| %>
    <li>
      <%= link_to game.name, game_path(game) %>
    </li>
  <% end %>
</ul>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>