config/routes.rb
MindGame::Application.routes.draw do

  get "set_language/english"

  get "set_language/hebrew"

  get "instructions/create"

  get "games/show"

  get "games/index"

  get "statistics/create"

root to: 'static_pages#home'

resources :games
resources :instructions
resources :statistics
resources :therapists
resources :patients do
  get 'show_details_to_therapist', :on => :member
end

resources :sessions, only: [:new, :create, :destroy]

get '/help',    to: 'static_pages#help'
get '/about',   to: 'static_pages#about'
get '/contact', to: 'static_pages#contact'

get '/signup', to: 'therapists#new'
get '/patient_signup', to: 'patients#new'

get '/signin',  to: 'sessions#new'
get '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.he.html.erb
<footer class="footer" >
  <small>
מופעל ע"י ניר לוי
  </small>
  <nav>
    <ul>
      <li><%= link_to "אודות",   about_path %></li>
      <li><%= link_to "צור קשר", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_footer.html.erb
<footer class="footer" >
  <small>
    by Nir Levi
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.he.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Brain Tracker", root_path, id: "logo" %>
      <nav>
        <p id='locale_set'>
          <%= link_to_unless I18n.locale == :en, "English", set_language_english_path %>
          |
          <%= link_to_unless I18n.locale == :he, "עברית", set_language_hebrew_path %>
        </p>
        <ul class="nav pull-right">
          <li><%= link_to "דף הבית", root_path %></li>
          <li><%= link_to "עזרה", help_path %></li>
          <li><%= link_to "משחקים", games_path%></li>
          <% if signed_in? %>
            
                <li><%= link_to "עמוד פרופיל", user_path(current_user) %></li>
                <li><%= link_to "הגדרות", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "התנתק", signout_path, method: "delete" %>
                </li>
    
          <% else %>
            <li><%= link_to "התחבר", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Brain Tracker", root_path, id: "logo" %>
      <nav>
        <p id='locale_set'>
          <%= link_to_unless I18n.locale == :en, "English", set_language_english_path %>
          |
          <%= link_to_unless I18n.locale == :he, "עברית", set_language_hebrew_path %>
        </p>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Games", games_path %></li>
          <% if signed_in? %>
            
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
    
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html <%= p('dir=rtl') unless I18n.locale == :en%>>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <script type="text/javascript">
    var user = <%= current_user.nil? ? 0 : current_user.id %> ;
    </script>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application", "highcharts" %>
    <%= yield(:javascripts) %>
    <%= yield(:stylesheets) %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" style="margin-top: 50px">
      <% flash.each do |key, value| %>
         <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>